kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # https://github.com/kubernetes-sigs/kind/releases
  - role: control-plane
    image: kindest/node:${KIND_NODE_VERSION}
  - role: worker
    image: kindest/node:${KIND_NODE_VERSION}
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 3201${i}
        hostPort: 3201${i}
        protocol: TCP
      - containerPort: 3202${i}
        hostPort: 3202${i}
        protocol: TCP
      - containerPort: 3203${i}
        hostPort: 3203${i}
        protocol: TCP
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        authorization-mode: "AlwaysAllow"
